---
- name: Crea y Configura VCN
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files: vault.yaml

  tasks:
  - name: Lista Subnet
    oracle.oci.oci_network_subnet_facts:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "CI-subnet"
    register: sb_resultado

  - set_fact:
      sb_id: "{{ sb_resultado.subnets[0].id }}"

  - name: Crea Instancia de Contenedor
    oracle.oci.oci_container_instances_container_instance:
      compartment_id: "{{ compartment_ocid }}"
      shape: "CI.Standard.E4.Flex"
      shape_config: 
        ocpus: "1"
        memory_in_gbs: "1"
      containers:
      - image_url: "docker.io/nginx:latest"
        display_name: "container-test"
      vnics:
      - subnet_id: "{{ sb_id }}"

