---
- name: Crea y Container Instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files: vault.yaml

  tasks:
  - name: Lista Subnet
    oracle.oci.oci_network_subnet_facts:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "CI-subnet"
    register: sb_resultado

  - set_fact:
      sb_id: "{{ sb_resultado.subnets[0].id }}"

  - name: Lista Availability Domains
    oracle.oci.oci_identity_availability_domain_facts:
      compartment_id: "{{ compartment_ocid }}"
    register: ad_resultado

  - debug:
      msg: "{{ ad_resultado.availability_domains[0].name }}"

  - name: Crea Instancia de Contenedor
    oracle.oci.oci_container_instances_container_instance:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "GP-Instance"
#      availability_domain: "{{ oci_resultado }}"
      availability_domain: "lkFW:SA-SANTIAGO-1-AD-1"
      shape: "CI.Standard.E4.Flex"
      shape_config: 
        ocpus: "1"
        memory_in_gbs: "1"
      containers:
      - image_url: "nginx:latest"
        display_name: "containertest"
      vnics:
      - subnet_id: "{{ sb_id }}"

