---
- name: Crea Registry de Contenedores
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files: vault.yaml

  tasks:
  - name: Crea Registry
    oracle.oci.oci_data_connectivity_registry:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "ciregistry"
