---
- name: Crea Instancia Autonomous Database Allways Free
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files: vault.yaml

  tasks:
  - name: Crea ADB (Always Free)
    oracle.oci.oci_database_autonomous_database:
        compartment_id: "{{ compartment_ocid }}"
        cpu_core_count: "1"
        display_name: "container-instance-adb"
        admin_password: "{{ admin_password }}"
        db_name: "ciadb"
        data_storage_size_in_tbs: "1"
        #is_free_tier: true
        state: 'present'
    register: resultado
