---
- name: Elimina VCN
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files: ../vault.yaml

  tasks:
  - name: Lista VCN
    oracle.oci.oci_network_vcn_facts:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "CI-VCN"
    register: vcn_resultado

  - set_fact:
      vcns_id: "{{ vcn_resultado.vcns[0].id }}"

  - set_fact:
          dr_id: "{{ vcn_resultado.vcns[0].default_route_table_id }}"

  - name: Update default route table to drop reference to internet gateway
    oracle.oci.oci_network_route_table:
      id: "{{ rt_id }}"
      route_rules: []
#
#  - name: Lista Route Table
#    oracle.oci.oci_network_route_table_facts:
#       compartment_id: "{{ compartment_ocid }}"
#       vcn_id: "{{ vcns_id }}"
#    register: rt_resultado
#
#  - set_fact:
#      rt_id: "{{ rt_resultado.route_tables[0].id }}"
#
#  - name: Elimina Route Table
#    oracle.oci.oci_network_route_table:
#       rt_id: "{{ rt_id }}"
#       state: 'absent'
#    register: resultado
