---
- name: Elimina VCN
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files: ../vault.yaml

  tasks:
  - name: Lista VCN
    oracle.oci.oci_network_vcn_facts:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "CI-VCN"
    register: vcn_resultado

  - set_fact:
      vcns_id: "{{ vcn_resultado.vcns[0].id }}"

  - set_fact:
      dr_id: "{{ vcn_resultado.vcns[0].default_route_table_id }}"

  - name: Update Default Route Para Remover Internet Gateway
    oracle.oci.oci_network_route_table:
      id: "{{ dr_id }}"
      route_rules: []

  - name: Elimina VCN
    oracle.oci.oci_network_vcn:
      vcn_id: "{{ vcns_id }}"
      state: absent
